{{- if or .Values.enterprise.adminApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headroom.fullname" . }}-secrets
  labels:
    {{- include "headroom.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.enterprise.adminApiKey }}
  admin-api-key: {{ .Values.enterprise.adminApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
