"""Portable product evidence and activation receipts.

This module joins existing proof surfaces without upgrading local evidence into
claims it cannot support. The JSON payload is intentionally dependency-light so
it can be generated by a normal CLI installation and forwarded as one file.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

DOWNSTREAM_TASK_METRICS = {
    "accuracy",
    "accuracy_normalized",
    "bleu_acc",
    "exact_match",
    "exact_match_flexible-extract",
    "ground_truth_match",
    "pass@1",
}


def _round_usd(value: float) -> float:
    return round(value, 6)


def _row_source_usd(row: dict[str, Any]) -> dict[str, float]:
    explicit = row.get("savings_by_source_usd")
    if isinstance(explicit, dict) and explicit:
        return {str(source): float(value or 0.0) for source, value in explicit.items()}

    compression = float(row.get("compression_savings_usd", 0.0) or 0.0)
    cache = float(row.get("cache_savings_usd", 0.0) or 0.0)
    total = float(row.get("cost_savings_usd", 0.0) or 0.0)
    if total and not compression and not cache:
        compression = total
    result: dict[str, float] = {}
    if compression:
        result["cutctx_compression"] = compression
    if cache:
        result["provider_prompt_cache"] = cache
    return result


def aggregate_savings_receipt(rows: list[dict[str, Any]]) -> dict[str, Any]:
    """Aggregate persisted request rows using additive source attribution."""
    if not rows:
        return {
            "status": "no_data",
            "requests": 0,
            "tokens_saved": 0,
            "usd_saved": 0.0,
            "savings_by_source_tokens": {},
            "savings_by_source_usd": {},
        }

    source_tokens: dict[str, int] = {}
    source_usd: dict[str, float] = {}
    for row in rows:
        token_sources = row.get("savings_by_source_tokens") or {}
        if isinstance(token_sources, dict):
            for source, value in token_sources.items():
                source_tokens[str(source)] = source_tokens.get(str(source), 0) + int(value or 0)
        for source, value in _row_source_usd(row).items():
            source_usd[source] = source_usd.get(source, 0.0) + value

    attributed_tokens = sum(source_tokens.values())
    row_tokens = sum(int(row.get("tokens_saved", 0) or 0) for row in rows)
    return {
        "status": "available",
        "requests": len(rows),
        "tokens_saved": attributed_tokens if source_tokens else row_tokens,
        "usd_saved": _round_usd(sum(source_usd.values())),
        "savings_by_source_tokens": dict(sorted(source_tokens.items())),
        "savings_by_source_usd": {
            source: _round_usd(value) for source, value in sorted(source_usd.items())
        },
    }


def _parse_timestamp(value: Any) -> datetime | None:
    if not isinstance(value, str) or not value:
        return None
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _read_json_object(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("artifact must contain a JSON object")
    return payload


def _artifact(root: Path, relative_path: str) -> dict[str, Any]:
    path = root / relative_path
    if not path.is_file():
        return {"status": "unavailable", "reason": f"{relative_path} was not found"}
    try:
        payload = _read_json_object(path)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return {"status": "unavailable", "reason": f"{relative_path} is invalid: {exc}"}
    return {
        "status": "available",
        "path": relative_path,
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "payload": payload,
    }


def _is_downstream_task_report(payload: dict[str, Any]) -> bool:
    benchmarks = payload.get("benchmarks")
    if not isinstance(benchmarks, list):
        return False
    for benchmark in benchmarks:
        if not isinstance(benchmark, dict):
            continue
        if benchmark.get("baseline_score") is not None and benchmark.get("cutctx_score") is not None:
            return True
        if str(benchmark.get("metric", "")).lower() in DOWNSTREAM_TASK_METRICS:
            return True
    return False


def select_downstream_task_report(root: Path) -> dict[str, Any] | None:
    """Select the newest report that measures a downstream task outcome."""
    candidates: list[tuple[datetime, Path, dict[str, Any]]] = []
    artifacts = root / "artifacts"
    if not artifacts.exists():
        return None
    for path in artifacts.glob("**/results.json"):
        try:
            payload = _read_json_object(path)
        except (OSError, ValueError, json.JSONDecodeError):
            continue
        if not _is_downstream_task_report(payload):
            continue
        timestamp = _parse_timestamp(payload.get("timestamp")) or datetime.fromtimestamp(
            path.stat().st_mtime, tz=timezone.utc
        )
        candidates.append((timestamp, path, payload))
    if not candidates:
        return None
    _, path, payload = max(candidates, key=lambda candidate: candidate[0])
    return {
        "status": "available",
        "path": str(path.relative_to(root)),
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "payload": payload,
    }


def _assurance_evidence() -> dict[str, Any]:
    try:
        from cutctx.assurance import EvidenceLedger

        path = EvidenceLedger._default_path().expanduser()
        if not path.is_file():
            return {"status": "unavailable", "reason": "no local assurance ledger was found"}
        ledger = EvidenceLedger(path=path)
        return {
            "status": "available",
            "path": str(path),
            "chain": ledger.verify_chain(),
            "stats": ledger.stats(),
        }
    except Exception as exc:  # pragma: no cover - defensive around operator state
        return {"status": "unavailable", "reason": f"assurance ledger could not be read: {exc}"}


def _release_posture(root: Path) -> dict[str, Any]:
    """Evaluate release posture from its hashed manifest and bundle now."""
    manifest_path = root / "artifacts" / "benchmark-release-manifest.json"
    bundle_path = root / "artifacts" / "benchmark-release-bundle.json"
    if not manifest_path.is_file() or not bundle_path.is_file():
        return {
            "status": "unavailable",
            "reason": "release evidence integrity cannot be verified without its manifest and bundle",
        }
    try:
        from cutctx.evals.release_evidence import evaluate_release_evidence

        payload = evaluate_release_evidence(root=root)
    except Exception as exc:
        return {
            "status": "unavailable",
            "reason": f"release evidence integrity validation failed: {exc}",
        }
    return {
        "status": "available",
        "artifacts": [
            {
                "path": str(path.relative_to(root)),
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            }
            for path in (manifest_path, bundle_path)
        ],
        "payload": payload,
    }


def build_product_evidence(
    *,
    root: Path,
    savings_rows: list[dict[str, Any]],
    days: int = 7,
    now: datetime | None = None,
) -> dict[str, Any]:
    """Build the canonical portable evidence payload."""
    generated_at = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    ordered_rows = sorted(
        savings_rows,
        key=lambda row: _parse_timestamp(row.get("timestamp")) or datetime.max.replace(tzinfo=timezone.utc),
    )
    first_request = aggregate_savings_receipt(ordered_rows[:1])
    if ordered_rows:
        first_request["timestamp"] = ordered_rows[0].get("timestamp")
    period = aggregate_savings_receipt(ordered_rows)
    period["period_days"] = days

    downstream = select_downstream_task_report(root) or {
        "status": "unavailable",
        "reason": "no downstream task-quality suite artifact was found",
    }
    evidence = {
        "downstream_task_quality": downstream,
        "compression_verification": _artifact(root, "artifacts/verify-report-release.json"),
        "model_routing": _artifact(root, "artifacts/model-routing-quality.json"),
        "release_posture": _release_posture(root),
        "assurance": _assurance_evidence(),
    }

    limitations: list[str] = []
    if downstream["status"] != "available":
        limitations.append("Downstream task-quality evidence is unavailable; compression fidelity is not a substitute.")
    release_payload = evidence["release_posture"].get("payload", {})
    if evidence["release_posture"]["status"] != "available":
        limitations.append(
            "Release evidence integrity is unavailable or invalid; no release posture is claimed."
        )
    elif not release_payload.get("market_claim_eligible", False):
        limitations.append("External market-claim eligibility is not established by this local receipt.")
    if period["status"] == "no_data":
        limitations.append("No persisted request savings are available for the selected period.")
    if evidence["assurance"]["status"] != "available":
        limitations.append("Context Assurance chain evidence is unavailable on this machine.")

    return {
        "schema_version": 1,
        "generated_at": generated_at.isoformat(),
        "period_days": days,
        "activation": {"first_request": first_request, "period": period},
        "evidence": evidence,
        "limitations": limitations,
    }


def render_product_evidence_markdown(payload: dict[str, Any]) -> str:
    """Render a concise buyer-readable view of a product evidence payload."""
    first = payload["activation"]["first_request"]
    period = payload["activation"]["period"]
    evidence = payload["evidence"]
    lines = [
        "# Cutctx Product Evidence Receipt",
        "",
        f"Generated: {payload['generated_at']}",
        "",
        "## Activation",
        "",
    ]
    if first["status"] == "available":
        lines.append(
            f"- First request: {first['tokens_saved']:,} tokens and ${first['usd_saved']:,.4f} saved."
        )
    else:
        lines.append("- First request: No persisted request savings are available.")
    if period["status"] == "available":
        lines.append(
            f"- Last {period['period_days']} days: {period['requests']:,} requests, "
            f"{period['tokens_saved']:,} tokens and ${period['usd_saved']:,.4f} saved."
        )
    else:
        lines.append(
            f"- Last {period['period_days']} days: No persisted request savings are available."
        )

    lines.extend(["", "## Evidence", ""])
    labels = {
        "downstream_task_quality": "Downstream task quality",
        "compression_verification": "Compression verification",
        "model_routing": "Model routing safety",
        "release_posture": "Release posture",
        "assurance": "Context Assurance",
    }
    for key, label in labels.items():
        item = evidence[key]
        detail = item.get("path") or item.get("reason") or "validated manifest and bundle"
        lines.append(f"- {label}: **{item['status']}** — {detail}")

    lines.extend(["", "## Limitations", ""])
    lines.extend(f"- {limitation}" for limitation in payload.get("limitations", []))
    return "\n".join(lines) + "\n"
