apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cutctx-pvc
  namespace: cutctx
  labels:
    app.kubernetes.io/name: cutctx-proxy
    app.kubernetes.io/component: proxy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
