"""Training schemas for the data flywheel.

Defines the structure of training examples generated by the label builder.
"""

from dataclasses import dataclass
from enum import Enum


class ExampleLabel(Enum):
    SHOULD_KEEP = "should_keep"
    SAFE_TO_DROP = "safe_to_drop"


@dataclass
class TrainingExample:
    """A fully materialized training example.

    Contains the original offset data along with the inferred label.
    NO RAW TEXT is stored here. This must be joined with the original payload
    in a secure, ephemeral training environment.
    """

    episode_id: str
    tenant_id: str
    label: ExampleLabel

    # Context features
    original_size: int
    compressed_size: int
    start_line: int
    end_line: int

    # Metadata
    session_id: str
    timestamp_ts: float
