{{- if or .Values.enterprise.adminApiKey .Values.enterprise.proxyApiKey .Values.enterprise.clientApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cutctx.fullname" . }}-secrets
  labels:
    {{- include "cutctx.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.enterprise.adminApiKey }}
  admin-api-key: {{ .Values.enterprise.adminApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.enterprise.proxyApiKey }}
  proxy-api-key: {{ .Values.enterprise.proxyApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.enterprise.clientApiKey }}
  client-api-key: {{ .Values.enterprise.clientApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
