#!/usr/bin/env python3
"""Catch accidentally line-collapsed source and docs.

This is intentionally small and dependency-free so it can run in pre-commit
before heavier formatters are installed.
"""

from __future__ import annotations

import subprocess
import sys
import tokenize
from pathlib import Path

TEXT_SUFFIXES = {
    ".json",
    ".md",
    ".mdx",
    ".py",
    ".pyi",
    ".toml",
    ".txt",
    ".yaml",
    ".yml",
}

SKIP_PARTS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "artifacts",
    "build",
    "dashboard/dist",
    "dist",
    "node_modules",
    "target",
}

MAX_PROSE_LINE = 220
MAX_PY_LINE = 180


def _tracked_files() -> list[Path]:
    result = subprocess.run(
        ["git", "ls-files"],
        check=True,
        capture_output=True,
        text=True,
    )
    return [Path(line) for line in result.stdout.splitlines() if line]


def _should_skip(path: Path) -> bool:
    normalized = path.as_posix()
    if path.name == "CHANGELOG.md":
        return True
    if normalized == "docs/security/SOC2_CONTROLS.md":
        return True
    return any(part in normalized for part in SKIP_PARTS)


def _is_generated(path: Path, text: str) -> bool:
    generated_markers = (
        "@generated",
        "auto-generated",
        "automatically generated",
        "generated by",
    )
    head = "\n".join(text.splitlines()[:8]).lower()
    return any(marker in head for marker in generated_markers)


def _check_markdown_line(path: Path, line_no: int, line: str) -> str | None:
    stripped = line.strip()
    if not stripped or stripped.startswith("|"):
        return None
    if "http://" in stripped or "https://" in stripped:
        return None
    if len(line) > MAX_PROSE_LINE:
        return f"{path}:{line_no}: line looks collapsed ({len(line)} chars)"
    return None


def _python_semicolon_lines(text: str) -> set[int]:
    lines: set[int] = set()
    tokens = tokenize.generate_tokens(iter(text.splitlines(keepends=True)).__next__)
    for token in tokens:
        if token.type == tokenize.OP and token.string == ";":
            lines.add(token.start[0])
    return lines


def _check_python_line(
    path: Path, line_no: int, line: str, semicolon_lines: set[int]
) -> str | None:
    stripped = line.strip()
    if "# noqa" in stripped or "# type:" in stripped:
        return None
    if len(line) > MAX_PY_LINE:
        return f"{path}:{line_no}: Python line too long for safe editing ({len(line)} chars)"
    if line_no in semicolon_lines:
        return f"{path}:{line_no}: avoid semicolon-collapsed Python statements"
    return None


def _check_file(path: Path) -> list[str]:
    if path.suffix not in TEXT_SUFFIXES or _should_skip(path) or not path.exists():
        return []

    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return []

    if _is_generated(path, text):
        return []

    failures: list[str] = []
    in_fence = False
    semicolon_lines = _python_semicolon_lines(text) if path.suffix in {".py", ".pyi"} else set()
    for line_no, line in enumerate(text.splitlines(), 1):
        if path.suffix in {".md", ".mdx"} and line.strip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        failure = (
            _check_python_line(path, line_no, line, semicolon_lines)
            if path.suffix in {".py", ".pyi"}
            else _check_markdown_line(path, line_no, line)
        )
        if failure:
            failures.append(failure)
    return failures


def main(argv: list[str]) -> int:
    paths = [Path(arg) for arg in argv[1:]] if len(argv) > 1 else _tracked_files()
    failures: list[str] = []
    for path in paths:
        failures.extend(_check_file(path))

    if failures:
        print("Text hygiene check failed:")
        for failure in failures:
            print(f"  {failure}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
